[package]
name = "brief"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = "0.8.23"
pulldown-cmark = { version = "0.13", default-features = false }
notify = "8"
notify-debouncer-mini = { version = "0.7", default-features = false }

[lib]
name = "brief"
path = "src/lib.rs"

[[bin]]
name = "brief"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
