//! `brief-web init` — write a minimal project skeleton.

use std::fs;
use std::path::Path;

pub struct ScaffoldOpts {
    pub multi_page: bool,
    pub force: bool,
}

pub fn create(dir: &Path, opts: &ScaffoldOpts) -> Result<(), String> {
    fs::create_dir_all(dir).map_err(|e| format!("cannot create {}: {}", dir.display(), e))?;
    let src = dir.join("src");
    fs::create_dir_all(&src).map_err(|e| format!("cannot create {}: {}", src.display(), e))?;

    write(&dir.join("book.toml"), BOOK_TOML, opts.force)?;

    if opts.multi_page {
        write(&src.join("SUMMARY.brf"), SUMMARY_BRF, opts.force)?;
        write(&src.join("index.brf"), INDEX_MULTI_BRF, opts.force)?;
        write(
            &src.join("getting-started.brf"),
            GETTING_STARTED_BRF,
            opts.force,
        )?;
    } else {
        write(&src.join("index.brf"), INDEX_SINGLE_BRF, opts.force)?;
    }

    let gitignore = dir.join(".gitignore");
    if !gitignore.exists() {
        fs::write(&gitignore, "dist/\n")
            .map_err(|e| format!("cannot write {}: {}", gitignore.display(), e))?;
    }

    Ok(())
}

fn write(path: &Path, content: &str, force: bool) -> Result<(), String> {
    if path.exists() && !force {
        return Err(format!(
            "{} already exists; pass --force to overwrite",
            path.display()
        ));
    }
    fs::write(path, content).map_err(|e| format!("cannot write {}: {}", path.display(), e))
}

const BOOK_TOML: &str = r#"[book]
title = "My Brief site"
description = "A site built with brief-web."
authors = []

[build]
src = "src"
out = "dist"

[site]
base_url = "/"

[server]
host = "127.0.0.1"
port = 3000
"#;

const INDEX_SINGLE_BRF: &str = r#"# Welcome

This page was generated by `brief-web init`.

Run `brief-web serve` and visit http://127.0.0.1:3000 to see it live.

## Next steps

- Edit `src/index.brf` and watch the page reload automatically.
- Convert this to a multi-page site by adding `src/SUMMARY.brf`.
"#;

const SUMMARY_BRF: &str = r#"# Summary

- @page[index.brf](Introduction)
- @page[getting-started.brf](Getting Started)
"#;

const INDEX_MULTI_BRF: &str = r#"# Introduction

Welcome to your new Brief site.

This is a multi-page project: `src/SUMMARY.brf` describes the navigation,
and each list item points to a `.brf` file under `src/`.

See @page[getting-started.brf](Getting Started) for a quick tour.
"#;

const GETTING_STARTED_BRF: &str = r#"# Getting Started

Run `brief-web serve` from the project root.

## Editing pages

Edit any `.brf` file under `src/` and your browser will reload automatically.

## Linking between pages

Use the `@page[...]` shortcode:

```brief
See @page[index.brf](the introduction) for more.
```
"#;
