[package]
name    = "brief-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap       = { version = "4", features = ["derive"] }
brief-core = { path = "../brief-core" }
mimalloc   = "0.1"
similar    = "2"

[[bin]]
name = "brief"
path = "src/main.rs"

[dev-dependencies]
tempfile = "3"
